openapi: '3.0.5'

info:
  title: API for grocery management
  description: OpenAPI Specification for the API
  version: 1.0.0
servers:
  - url: http://localhost:4200/api/v1
    description: Local server
tags:
  - name: Role
    description: Operations related to roles
paths:
  /role/create:
    $ref: './paths/roles.yml#/PathCreate'
  /role/update:
    $ref: './paths/roles.yml#/PathUpdate'
  /role/delete:
    $ref: './paths/roles.yml#/PathDelete'
  /role/get:
    $ref: './paths/roles.yml#/PathGet'