// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	ID          *string    `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name        string     `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Description *string    `gorm:"column:description;type:text" json:"description"`
	ParentID    *string    `gorm:"column:parent_id;type:uuid" json:"parent_id"`
	IsActive    *bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	CreatedBy   *string    `gorm:"column:created_by;type:uuid" json:"created_by"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
