// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameContact = "contacts"

// Contact mapped from table <contacts>
type Contact struct {
	ID          string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	VendorID    string         `gorm:"column:vendor_id" json:"vendor_id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	PhoneNumber string         `gorm:"column:phone_number" json:"phone_number"`
	Email       string         `gorm:"column:email" json:"email"`
	Address     string         `gorm:"column:address" json:"address"`
	Designation string         `gorm:"column:designation" json:"designation"`
	Department  string         `gorm:"column:department" json:"department"`
	DateOfBirth time.Time      `gorm:"column:date_of_birth" json:"date_of_birth"`
	FirstName   string         `gorm:"column:first_name" json:"first_name"`
	LastName    string         `gorm:"column:last_name" json:"last_name"`
	Position    string         `gorm:"column:position" json:"position"`
	Status      string         `gorm:"column:status;not null;default:active" json:"status"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedBy   string         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy   string         `gorm:"column:updated_by" json:"updated_by"`
	DeletedBy   string         `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName Contact's table name
func (*Contact) TableName() string {
	return TableNameContact
}
