// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInventory = "inventory"

// Inventory mapped from table <inventory>
type Inventory struct {
	ID              string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	GroceryID       string    `gorm:"column:grocery_id;not null" json:"grocery_id"`
	ProductID       string    `gorm:"column:product_id;not null" json:"product_id"`
	Sku             string    `gorm:"column:sku;not null" json:"sku"`
	Barcode         string    `gorm:"column:barcode;not null" json:"barcode"`
	CategoryID      string    `gorm:"column:category_id;not null" json:"category_id"`
	ProductName     string    `gorm:"column:product_name;not null" json:"product_name"`
	Quantity        int32     `gorm:"column:quantity;not null" json:"quantity"`
	UnitPrice       float64   `gorm:"column:unit_price;not null" json:"unit_price"`
	ExpiryDate      time.Time `gorm:"column:expiry_date" json:"expiry_date"`
	ReorderLevel    int32     `gorm:"column:reorder_level;default:10" json:"reorder_level"`
	InStock         bool      `gorm:"column:in_stock;default:true" json:"in_stock"`
	InventoryStatus string    `gorm:"column:inventory_status;not null;default:available" json:"inventory_status"`
	CreatedBy       string    `gorm:"column:created_by" json:"created_by"`
	UpdatedBy       string    `gorm:"column:updated_by" json:"updated_by"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Inventory's table name
func (*Inventory) TableName() string {
	return TableNameInventory
}
