// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameInventoryTransaction = "inventory_transaction"

// InventoryTransaction mapped from table <inventory_transaction>
type InventoryTransaction struct {
	ID              string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	GroceryID       string    `gorm:"column:grocery_id;not null" json:"grocery_id"`
	ProductID       string    `gorm:"column:product_id;not null" json:"product_id"`
	Sku             string    `gorm:"column:sku;not null" json:"sku"`
	Barcode         string    `gorm:"column:barcode;not null" json:"barcode"`
	CategoryID      string    `gorm:"column:category_id;not null" json:"category_id"`
	OldQuantity     int32     `gorm:"column:old_quantity;not null" json:"old_quantity"`
	NewQuantity     int32     `gorm:"column:new_quantity;not null" json:"new_quantity"`
	QuantityChange  int32     `gorm:"column:quantity_change;not null" json:"quantity_change"`
	UnitPrice       float64   `gorm:"column:unit_price;not null" json:"unit_price"`
	TransactionType string    `gorm:"column:transaction_type;not null" json:"transaction_type"`
	TransactionDate time.Time `gorm:"column:transaction_date;default:CURRENT_TIMESTAMP" json:"transaction_date"`
	CreatedBy       string    `gorm:"column:created_by" json:"created_by"`
	UpdatedBy       string    `gorm:"column:updated_by" json:"updated_by"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName InventoryTransaction's table name
func (*InventoryTransaction) TableName() string {
	return TableNameInventoryTransaction
}
