// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMigration = "migrations"

// Migration mapped from table <migrations>
type Migration struct {
	ID        int32     `gorm:"column:id;not null" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	AppliedAt time.Time `gorm:"column:applied_at;default:CURRENT_TIMESTAMP" json:"applied_at"`
}

// TableName Migration's table name
func (*Migration) TableName() string {
	return TableNameMigration
}
