// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermission = "permissions"

// Permission mapped from table <permissions>
type Permission struct {
	ID          string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description string         `gorm:"column:description" json:"description"`
	Status      string         `gorm:"column:status;not null;default:active" json:"status"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedBy   string         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy   string         `gorm:"column:updated_by" json:"updated_by"`
	DeletedBy   string         `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
