// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRolePermission = "role_permissions"

// RolePermission mapped from table <role_permissions>
type RolePermission struct {
	ID           string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	RoleID       string         `gorm:"column:role_id;not null" json:"role_id"`
	PermissionID string         `gorm:"column:permission_id;not null" json:"permission_id"`
	Status       string         `gorm:"column:status;not null;default:active" json:"status"`
	CreatedAt    time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedBy    string         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy    string         `gorm:"column:updated_by" json:"updated_by"`
	DeletedBy    string         `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
