// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	GroceryID    string         `gorm:"column:grocery_id" json:"grocery_id"`
	Username     string         `gorm:"column:username;not null" json:"username"`
	Email        string         `gorm:"column:email;not null" json:"email"`
	PasswordHash string         `gorm:"column:password_hash;not null" json:"password_hash"`
	FirstName    string         `gorm:"column:first_name" json:"first_name"`
	LastName     string         `gorm:"column:last_name" json:"last_name"`
	PhoneNumber  string         `gorm:"column:phone_number" json:"phone_number"`
	Role         string         `gorm:"column:role;not null;default:customer" json:"role"`
	IsActive     bool           `gorm:"column:is_active;default:true" json:"is_active"`
	LastLogin    time.Time      `gorm:"column:last_login" json:"last_login"`
	CreatedAt    time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedBy    string         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy    string         `gorm:"column:updated_by" json:"updated_by"`
	DeletedBy    string         `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
