// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameVendor = "vendors"

// Vendor mapped from table <vendors>
type Vendor struct {
	ID          string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Code        string         `gorm:"column:code;not null" json:"code"`
	Description string         `gorm:"column:description" json:"description"`
	PhoneNumber string         `gorm:"column:phone_number" json:"phone_number"`
	Email       string         `gorm:"column:email" json:"email"`
	Website     string         `gorm:"column:website" json:"website"`
	City        string         `gorm:"column:city" json:"city"`
	State       string         `gorm:"column:state" json:"state"`
	Country     string         `gorm:"column:country" json:"country"`
	Address     string         `gorm:"column:address" json:"address"`
	Status      string         `gorm:"column:status;not null;default:active" json:"status"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedBy   string         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy   string         `gorm:"column:updated_by" json:"updated_by"`
	DeletedBy   string         `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName Vendor's table name
func (*Vendor) TableName() string {
	return TableNameVendor
}
