/*
 * API for grocery management
 *
 * OpenAPI Specification for the API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"github.com/gin-gonic/gin"
)

type RoleAPI struct {
}

// Post /api/v1/role/create
// Create a new role 
func (api *RoleAPI) CreateRole(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/v1/role/delete
// Delete a role 
func (api *RoleAPI) DeleteRole(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/role/get
// Get all roles 
func (api *RoleAPI) GetAllRoles(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/v1/role/update
// Update an existing role 
func (api *RoleAPI) UpdateRole(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

