// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dto

import (
	"time"
)

// Defines values for BaseRoleStatus.
const (
	BaseRoleStatusActive   BaseRoleStatus = "active"
	BaseRoleStatusCanceled BaseRoleStatus = "canceled"
	BaseRoleStatusDeleted  BaseRoleStatus = "deleted"
	BaseRoleStatusInactive BaseRoleStatus = "inactive"
	BaseRoleStatusPending  BaseRoleStatus = "pending"
)

// Defines values for PaginationRequestOrder.
const (
	Asc  PaginationRequestOrder = "asc"
	Desc PaginationRequestOrder = "desc"
)

// Defines values for RoleRequestStatus.
const (
	RoleRequestStatusActive    RoleRequestStatus = "active"
	RoleRequestStatusCancelled RoleRequestStatus = "cancelled"
	RoleRequestStatusDeleted   RoleRequestStatus = "deleted"
	RoleRequestStatusInactive  RoleRequestStatus = "inactive"
	RoleRequestStatusPending   RoleRequestStatus = "pending"
	RoleRequestStatusReview    RoleRequestStatus = "review"
)

// Defines values for RoleUpdateRequestStatus.
const (
	Active    RoleUpdateRequestStatus = "active"
	Cancelled RoleUpdateRequestStatus = "cancelled"
	Deleted   RoleUpdateRequestStatus = "deleted"
	Inactive  RoleUpdateRequestStatus = "inactive"
	Pending   RoleUpdateRequestStatus = "pending"
	Review    RoleUpdateRequestStatus = "review"
)

// BaseRole Base role object with common properties
type BaseRole struct {
	CreatedAt   *time.Time      `json:"createdAt,omitempty"`
	CreatedBy   *string         `json:"createdBy,omitempty"`
	DeletedAt   *time.Time      `json:"deletedAt,omitempty"`
	DeletedBy   *string         `json:"deletedBy,omitempty"`
	Description string          `json:"description"`
	Name        string          `json:"name"`
	Status      *BaseRoleStatus `json:"status,omitempty"`
	UpdatedAt   *time.Time      `json:"updatedAt,omitempty"`
	UpdatedBy   *string         `json:"updatedBy,omitempty"`
}

// BaseRoleStatus defines model for BaseRole.Status.
type BaseRoleStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int32     `json:"code"`
	Details string    `json:"details"`
	Errors  *[]string `json:"errors,omitempty"`
	Message string    `json:"message"`
}

// GeneralArrayResponse General response object
type GeneralArrayResponse struct {
	// Code Response code
	Code *int        `json:"code,omitempty"`
	Data *[]BaseRole `json:"data,omitempty"`

	// Message Response message
	Message *string `json:"message,omitempty"`
}

// GeneralResponse General response object
type GeneralResponse struct {
	// Code Response code
	Code *int `json:"code,omitempty"`

	// Data Base role object with common properties
	Data *BaseRole `json:"data,omitempty"`

	// Message Response message
	Message *string `json:"message,omitempty"`
}

// PaginationRequest defines model for PaginationRequest.
type PaginationRequest struct {
	// Limit The number of items per page.
	Limit int `json:"limit"`

	// Order The order of sorting (asc or desc).
	Order *PaginationRequestOrder `json:"order,omitempty"`

	// Page The page number for pagination.
	Page int `json:"page"`

	// Sort The field to sort by.
	Sort *string `json:"sort,omitempty"`
}

// PaginationRequestOrder The order of sorting (asc or desc).
type PaginationRequestOrder string

// RoleRequest defines model for RoleRequest.
type RoleRequest struct {
	// Description A brief description of the role.
	Description string `json:"description"`

	// Name The name of the role.
	Name   string             `json:"name"`
	Status *RoleRequestStatus `json:"status,omitempty"`
}

// RoleRequestStatus defines model for RoleRequest.Status.
type RoleRequestStatus string

// RoleUpdateRequest defines model for RoleUpdateRequest.
type RoleUpdateRequest struct {
	// Description A brief description of the role.
	Description *string `json:"description,omitempty"`

	// Id The unique identifier of the role to be updated.
	Id string `json:"id"`

	// Name The name of the role.
	Name   *string                  `json:"name,omitempty"`
	Status *RoleUpdateRequestStatus `json:"status,omitempty"`
}

// RoleUpdateRequestStatus defines model for RoleUpdateRequest.Status.
type RoleUpdateRequestStatus string

// DeleteRoleParams defines parameters for DeleteRole.
type DeleteRoleParams struct {
	// Id The unique identifier of the role to be deleted.
	Id string `form:"id" json:"id"`
}

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleRequest

// GetAllRolesJSONRequestBody defines body for GetAllRoles for application/json ContentType.
type GetAllRolesJSONRequestBody = PaginationRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = RoleUpdateRequest
