/*
 * API for grocery management
 *
 * OpenAPI Specification for the API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type RoleUpdateRequest struct {

	// The unique identifier of the role to be updated.
	Id string `json:"id"`

	// The name of the role.
	Name string `json:"name,omitempty"`

	Status string `json:"status,omitempty"`

	// A brief description of the role.
	Description string `json:"description,omitempty"`
}
