/*
 * API for grocery management
 *
 * OpenAPI Specification for the API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

import (
	"time"
)

// BaseRole - Base role object with common properties
type BaseRole struct {

	Name string `json:"name"`

	Description string `json:"description"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	CreatedBy string `json:"createdBy,omitempty"`

	UpdatedBy string `json:"updatedBy,omitempty"`

	DeletedAt time.Time `json:"deletedAt,omitempty"`

	DeletedBy string `json:"deletedBy,omitempty"`
}
