/*
 * API for grocery management
 *
 * OpenAPI Specification for the API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type PaginationRequest struct {

	// The page number for pagination.
	Page int32 `json:"page"`

	// The number of items per page.
	Limit int32 `json:"limit"`

	// The field to sort by.
	Sort string `json:"sort,omitempty"`

	// The order of sorting (asc or desc).
	Order string `json:"order,omitempty"`
}
