/*
 * API for grocery management
 *
 * OpenAPI Specification for the API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

// GeneralArrayResponse - General response object
type GeneralArrayResponse struct {

	// Response code
	Code int32 `json:"code,omitempty"`

	// Response message
	Message string `json:"message,omitempty"`

	Data []BaseRole `json:"data,omitempty"`
}
