/*
 * API for grocery management
 *
 * OpenAPI Specification for the API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ErrorResponse struct {

	Code int32 `json:"code"`

	Message string `json:"message"`

	Details string `json:"details"`

	Errors []string `json:"errors,omitempty"`
}
